## MATRICES

In [2]:
#Creating a matrix
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]
             ])

In [4]:
print(A.shape)
print(A.ndim)
print(A.size)
print(A.dtype)

(3, 4)
2
12
int32


## Indexing and Slicing Matrices

In [5]:
#Single element: A[row,col]
print(A[0,0])
print(A[1,2])
print(A[-1,-1])

1
7
12


In [6]:
#slicing
print(A[1, :])

[5 6 7 8]


In [7]:
A[0:2,1:3]

array([[2, 3],
       [6, 7]])

## Creating Special Matrices

In [10]:
# zeros matrix
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# ones matrix
o = np.ones((2,3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# identity matrices
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# random values
r = np.random.randn(3,3)
r

array([[ 5.05508680e-01,  2.90866398e-01,  5.37707091e-02],
       [-7.59103879e-02, -4.11590999e-01, -1.53844732e+00],
       [-7.18594865e-02,  1.46666882e+00,  7.68829905e-04]])

In [16]:
# random values (uniform between 0 and 1)
m = np.random.rand(3,3)
m

array([[0.49965018, 0.56703034, 0.59227071],
       [0.58947172, 0.98157031, 0.93836153],
       [0.63164419, 0.32277698, 0.00376771]])

 ## Matrix multiplication

In [20]:
A = np.array([[1,2,3],
              [4,5,6]    
])   #shape(2,3)

B = np.array([[7,8],
              [9,10],
             [11,12]    
]) # shape(3,2)
C = A@B
D = np.dot(A,B)
E = np.matmul(A,B)

## Transpose

In [21]:
T = np.array([[1,2,3],
              [4,5,6]
    
])
print(T.T)

[[1 4]
 [2 5]
 [3 6]]


## Broadcasting

In [ ]:
# pattern 1: Matrix + scalar (scalar stretches to fill matrix)
A = n